import { foodPlaceholderImages } from "@/lib/placeholders/food-images";
import { jewelryPlaceholderImages } from "@/lib/placeholders/jewelry-images";
import { DEFAULT_VERTICAL_ID, type VerticalId } from "@/lib/verticals";

export const verticalContent = {
  jewelry: {
    authContextLabel: "استودیوی هوشمند طلا",
    authHint: "برای ساخت تصویر حرفه‌ای محصول وارد شوید",
    productName: "محصول",
    productTypeFieldLabel: "نوع محصول",
    productTypeHelp: "در صورت مغایرت تغییر دهید",
    galleryEmptyTitle: "هنوز عکسی در گالری ندارید.",
    galleryImageFallbackTitle: "تصویر محصول",
    galleryUploadLabel: "آپلود عکس",
    galleryCameraLabel: "دوربین",
    gallerySaveReferenceLabel: "ذخیره در نمونه‌ها",
    projectEmptyTitle: "هنوز خروجی تولید نشده است.",
    projectFallbackTitle: "پروژه محصول",
    projectResultAlt: "نمونه خروجی پروژه",
    newProjectSourceTitle: "آپلود عکس محصول",
    newProjectSizeTitle: "ابعاد و نوع محصول",
    newProjectStyleTitle: "انتخاب سبک",
    sourceReadyLabel: "انتخاب سریع از گالری",
    sourcePreparingLabel: "در حال آماده‌سازی عکس برای آپلود...",
    sourceErrorTitle: "عکس آماده نشد",
    supportingTriggerTitle: "محصولم جزئیات بیشتری دارد",
    supportingTriggerDescription: "اختیاری، فقط برای زاویه یا قفل و نگین پیچیده",
    supportingSectionTitle: "زاویه‌های کمکی",
    supportingSectionDescription: "اگر محصول از یک عکس کامل مشخص است، این بخش را رد کنید.",
    supportingAddLabel: "افزودن زاویه",
    supportingFallbackTitle: "زاویه کمکی محصول",
    sampleReferenceTitle: "عکس نمونه",
    uploadedSampleLabel: "نمونه آپلودی",
    processingSteps: ["تشخیص محصول", "پاک‌سازی زمینه", "ساخت خروجی نهایی"],
    qualityReviewTitle: "گزارش مشکل محصول",
    rawImageLabel: "عکس خام",
    finalImageLabel: "خروجی",
    placeholders: jewelryPlaceholderImages,
  },
  food: {
    authContextLabel: "Ovala Food",
    authHint: "برای ساخت عکس حرفه‌ای غذا و نوشیدنی وارد شوید",
    productName: "غذا یا نوشیدنی",
    productTypeFieldLabel: "نوع آیتم غذایی",
    productTypeHelp: "برای حفظ ظاهر غذا، نوع نزدیک‌تر را انتخاب کنید",
    galleryEmptyTitle: "هنوز عکس غذا یا نوشیدنی در گالری ندارید.",
    galleryImageFallbackTitle: "عکس غذا یا نوشیدنی",
    galleryUploadLabel: "آپلود عکس",
    galleryCameraLabel: "دوربین",
    gallerySaveReferenceLabel: "ذخیره در نمونه‌ها",
    projectEmptyTitle: "هنوز خروجی تولید نشده است.",
    projectFallbackTitle: "پروژه محصول",
    projectResultAlt: "نمونه خروجی غذا و نوشیدنی",
    newProjectSourceTitle: "آپلود عکس محصول",
    newProjectSizeTitle: "ابعاد و نوع محصول",
    newProjectStyleTitle: "انتخاب سبک",
    sourceReadyLabel: "انتخاب سریع از گالری",
    sourcePreparingLabel: "در حال آماده‌سازی عکس برای آپلود...",
    sourceErrorTitle: "عکس آماده نشد",
    supportingTriggerTitle: "آیتم از چند زاویه بهتر دیده می‌شود",
    supportingTriggerDescription: "اختیاری، برای بسته‌بندی، برچسب، بافت یا چیدمان بشقاب",
    supportingSectionTitle: "جزئیات کمکی",
    supportingSectionDescription: "اگر غذا یا نوشیدنی از یک عکس واضح است، این بخش را رد کنید.",
    supportingAddLabel: "افزودن جزئیات",
    supportingFallbackTitle: "جزئیات کمکی محصول",
    sampleReferenceTitle: "عکس نمونه",
    uploadedSampleLabel: "نمونه آپلودی",
    processingSteps: ["تشخیص غذا", "تنظیم نور و تازگی", "ساخت خروجی آماده منو"],
    qualityReviewTitle: "گزارش مشکل محصول",
    rawImageLabel: "عکس خام",
    finalImageLabel: "خروجی",
    placeholders: foodPlaceholderImages,
  },
} as const;

export type VerticalContent = (typeof verticalContent)[keyof typeof verticalContent];

export function getVerticalContent(vertical: VerticalId = DEFAULT_VERTICAL_ID): VerticalContent {
  return vertical === "food" ? verticalContent.food : verticalContent[DEFAULT_VERTICAL_ID];
}
