ALTER TABLE `Project`
  MODIFY `status` ENUM('PENDING', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED') NOT NULL DEFAULT 'QUEUED';

ALTER TABLE `GenerationBatch`
  MODIFY `status` ENUM('PENDING', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED') NOT NULL DEFAULT 'QUEUED';

UPDATE `Project`
SET `status` = 'QUEUED'
WHERE `status` = 'PENDING';

UPDATE `GenerationBatch`
SET `status` = 'QUEUED'
WHERE `status` = 'PENDING';

ALTER TABLE `Project`
  MODIFY `status` ENUM('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED') NOT NULL DEFAULT 'QUEUED';

ALTER TABLE `GenerationBatch`
  MODIFY `status` ENUM('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED') NOT NULL DEFAULT 'QUEUED';
